import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/packages/utils/cn";
import Providers from "./providers";

const fontSans = Geist({
  subsets: ['latin'],
  variable: '--font-sans'
})

const fontMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={cn(fontSans.variable, fontMono.variable)}
      suppressHydrationWarning  
    >
      <body
        className={`relative flex min-h-screen flex-col`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
